apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-store-service-ui
  labels:
    app: image-store-service-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-store-service-ui
  template:
    metadata:
      labels:
        app: image-store-service-ui
    spec:
      containers:
        - name: image-store-service-ui
          image: aravindhsz/image-store-service-ui:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: image-store-service-ui
  labels:
    app: image-store-service-ui
spec:
  type: NodePort
  selector:
    app: image-store-service-ui
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000    